[build-system]
requires = ["setuptools>=42", "Cython>=3.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyberry-framework"
version = "0.1.0"
dynamic = ["description", "readme", "authors"]
dependencies = [
    "granian",
    "cython",
    "setuptools"
]

[project.scripts]
pyberry = "pyberry.cli:main"
